library(lubridate)
library(dplyr)
PowerData<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE,colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
PowerData<-mutate(PowerData,DateTime=dmy_hms(paste(PowerData[,"Date"],PowerData[,"Time"])))
FebPowerData<-subset(PowerData,Date=="1/2/2007"|Date=="2/2/2007")
hist(FebPowerData$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.copy(png,"plot1.png")
dev.off()