library(lubridate)
library(dplyr)
PowerData<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors=FALSE,colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
PowerData<-mutate(PowerData,DateTime=dmy_hms(paste(PowerData[,"Date"],PowerData[,"Time"])))
FebPowerData<-subset(PowerData,Date=="1/2/2007"|Date=="2/2/2007")
par(mfcol=c(2,2))
with(FebPowerData,plot(DateTime,Global_active_power,xlab="",ylab="Global Active Power",pch=20,type="l"))
with(FebPowerData,plot(DateTime,Sub_metering_1,xlab="",ylab="Energy sub metering",type="l"))
with(FebPowerData,lines(DateTime,Sub_metering_2,col="red"))
with(FebPowerData,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright",cex=0.5,col=c("black","red","blue"),lty="solid",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(FebPowerData,plot(DateTime,Voltage,xlab="datetime",ylab="Voltage",pch=20,type="l"))
with(FebPowerData,plot(DateTime,Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",pch=20,type="l"))
dev.copy(png,file="plot4.png")
dev.off()